odilia-app/odilia

Cargo.lock, atspi/Cargo.toml, common/Cargo.toml, odilia/Cargo.toml, odilia/src/events/mod.rs, odilia/src/events/object.rs, odilia/src/main.rs
[`zbus`](https://crates.io/crates/zbus) 3.0 no longer relies on other async crates when using [`tokio`](https://tokio.rs), and has some other improvements too. However, when upgrading to it, we no longer receive any at-spi events for some reason.
```
new{}
open{}
0ms DEBUG Connecting to session bus
receive_msg{}
2ms DEBUG Connected to session bus, name=":1.388"
2ms DEBUG Getting a11y bus address from session bus
4ms DEBUG Got a11y bus address, address=unix:path=/run/user/1000/at-spi/bus_0,guid=996e378c20f46927fe9e222c63051013
4ms DEBUG Connecting to a11y bus
receive_msg{}
6ms DEBUG Connected to a11y bus, name=":1.148"
6ms DEBUG Connecting to speech-dispatcher
8ms DEBUG speech dispatcher initialisation successful
8ms DEBUG loading configuration file, …
```
=> Upgrade zbus to version 3.0.0

odilia/Cargo.toml, odilia/src/events/document.rs, odilia/src/events/mod.rs, odilia/src/events/object.rs, odilia/src/main.rs, odilia/src/state.rs
[View the Matrix discussion](https://matrix.to/#/!BVPeWFRhpOwtjxKvET:matrix.org/$vnhd45OeK-oEp9FrmAeOduC4s6MNnGr7hZ-s1Lx5geo?via=matrix.org&via=t2bot.io&via=lowerelements.club)
In short, I don't think it makes a lot of sense to use [Tokio](https://tokio.rs)'s multi-threaded executor (`rt-multi` feature) for this project. We're simply not handling enough IO for this to be worth it, and in some cases we pay a premium in synchronisation overhead and *especially* code readability / commplexity. It may also make Odilia less resource heavy in constrained environments, however I'm almost certain the difference will be negligible.
This PR drops the `rt-multi` executor in favor of `rt`, which is single-threaded. It also removes some synchronisation primitives, and gets rid of the global state, …
=> Use the Single Threaded Executor

atspi/src/accessible.rs, atspi/src/accessible_ext.rs, atspi/src/cache.rs, atspi/src/convertable.rs, atspi/src/events/mod.rs, atspi/src/interfaces.rs, atspi/src/lib.rs, odilia/src/events/mod.rs
Adds a new type to represent the set of AT-SPI interfaces an object can implement. This makes it safer and more efficient to check whether a particular object actually implement a given interface. Cached items will also take significantly less space in memory.
=> atspi: Add `InterfaceSet`

atspi/src/cache.rs
Follow-up of #25 
While helping investigate #7 I just realized that I forgot to update the `Cache` proxy to use the new `StateSet` type.
Is there a reason why not to create a plain struct with named fields for cached items? We could drop the ugly doc comments for `CacheStruct` then.
=> atspi: Fix states in Cache

README.md, atspi/README.md
The crates.io badge in the atspi crate is still not working because I didn't want to update the URL as I don't know what you have in mind @TTWNO .
FYI crates.io automatically generates badges. You can find the one for atspi at https://img.shields.io/crates/v/atspi.
So if you just want a regular badge, tell me and I'll update it as part of this PR.
=> Fix READMEs

odilia/src/state.rs
When one starts Odilia for the first time, the configuration file isn't actually copied, therefore the program crashes.
I am sure this is due to a misunderstanding of `xdg::BaseDirectories::place_config_file` which, as its name implies, just makes sur the parent directory on which to place the file is present...
=> Fix config file initialization

atspi/src/accessible.rs, atspi/src/events/mod.rs
Some types were lacking this. It's needed to write an AT-SPI server.
=> atspi: Derive `Serialize` on all types

atspi/src/interfaces.rs
I need this to easily compute which interfaces an object may have gained or lost between tree updates.
See [here](https://github.com/DataTriny/accesskit/blob/8b9dd35b707ac67c33f0c9f219649d418cbe5943/platforms/linux/src/adapter.rs#L136) for actual use.
=> atspi: impl `BitAnd` for `InterfaceSet`

atspi/src/events/document.rs, atspi/src/events/focus.rs, atspi/src/events/keyboard.rs, atspi/src/events/mod.rs, atspi/src/events/mouse.rs, atspi/src/events/object.rs, atspi/src/events/terminal.rs, atspi/src/events/window.rs, atspi/src/state.rs
I still haven't figured out the best way forward for this, but at least now it's possible to serialize events holding a `kind` which type is something other than `&str`. At least I'll be able to take advantage of this for AccessKit.
- Added serde support to the `State` type.
- Rearranged `EventBodyQT` (I don't see why we would need a borrowing version of this type, it's kind of a bug in Qt so you wouldn't want anybody to use it on the server-side).
- Updated signals to use `EventBody<&str>` (except object's `state_changed` which now takes `EventBody<State>`).
Hopefully this can spark ideas on how to better type-check these event related structs.
=> atspi: Make `EventBody` generic over serializable types for `kind`

atspi/src/socket.rs
It took me ages to figure out why my test app was no longer being registered by the AT-SPI registry since I switched to the `atspi` crate. I forgot that I had set the `default_path` and `default_service` attributes on my `SocketProxy` implementation. So I would suggest to add these back here too.
I am aware that `Socket` can also be implemented by providers, but I think it makes sense to have it pointing towards the registry by default. You aren't supposed to know where it is located (it's not documented anywhere afterall) unless you're an AT-SPI nerd!
=> atspi: Add default path and service name to SocketProxy

atspi/src/lib.rs
This moves the comment outside of the macro to restore its intended behaviour.
=> [atspi] Comment in global attribute macro confuses ra / clippy

README.md
setup-permissions.sh should be setup_permissions.sh and it need root permission to run the script.
=> fix filename typo and add sudo prefix

rustfmt.toml
This adds a rustfmt.toml with wome defaults.
Most importantly, it contains the link to the rustfmt settings docs.
=> [fmt] Add `rustfmt.toml`

Cargo.toml, odilia/src/main.rs
This adds a call to `atspi::set_session_accessibility`.
Applications may monitor `IsEnabled`  from `org.a11y.Status` on the session bus to dynamically support AT-SPI2 functionality. This makes sure those which do, know they should now expose their AT-SPI2 interfaces on the bus.
=> Set `IsEnabled` property on start-up

README.md, scripts/debug_start_sohkd.sh, scripts/odilia
Two commits address #78 to some extent. 
Sumary:
Commit 4be1247
Reduce number of steps to install:
- Changes cloning, compiling and installing to one command.
Fixes: install path.
Makes sure the instructions and the script assume the same:
- Changes compilation of `sohkd` to debug and copies the binary to `~/.cargo/biin`
- Modifies `debug_start_sohkd.sh` accordingly.
- Explains a bit more what it is we do.
Commit 1fa640b
Makes less assumptions on what the users install base looks like:
- Adds 'Prerequisite' notice in the README
Unclutter terminal:
- Reverts merged-launch of `Odilia` and `sohkd`.
Makes launching `sohkd` independent of the pwd:
- Adds `XDG_RUNTIME_DIR` and use path `~/.cargo/bin` to launch `sohkd`.
Makes launching `Odilia` independent of the pwd:
- Use `~/.cargo/bin` to …
=> Work on improving instructions

Cargo.toml
When https://github.com/odilia-app/atspi/pull/51 was merged, the `fix-name-of-text-changed-parameter` branch was deleted. So, currently on `main`, `odilia` fails to build:
```
❯ cargo build
error: failed to get `atspi` as a dependency of package `odilia-cache v0.1.0 (/home/sam/code/odilia/cache)`
Caused by:
failed to load source for dependency `atspi`
Caused by:
Unable to update https://github.com/odilia-app/atspi?branch=fix-name-of-text-changed-parameter
Caused by:
failed to find branch `fix-name-of-text-changed-parameter`
Caused by:
cannot locate remote-tracking branch 'origin/fix-name-of-text-changed-parameter'; class=Reference (4); code=NotFound (-3)
```
I imagine you'll want to get a release out for `atspi` and go back to tracking by version, but in the meantime, this will fix the …
=> Fix missing atspi dependency

README.md
=> readme.md: Fix spelling of 'environment'.

cache/src/lib.rs, input/examples/generate-json.rs, input/src/lib.rs, odilia/src/events/mod.rs, odilia/src/events/object.rs, odilia/src/main.rs, odilia/src/state.rs, tts/src/lib.rs
this is especially needed because without it, everyone else's pull requests will break on the CI step, requiring ignoring by maintainers, which is harder work because now we have to filter out what we know to be clippy errors related to legacy code, and what is new lints detected on new code, which no one should do
assuming this passes tests, it should be merged right away, and existing unmerged pull requests should afterwards rebase upon main
=> Fix-should-panic-lint

Cargo.lock, odilia/Cargo.toml, odilia/src/cli.rs, odilia/src/events/mod.rs, odilia/src/main.rs, odilia/src/state.rs
Odilia currently does not support cli args. When I first installed odilia I expected to be able to run `--help` to get some general info on the program. It is also useful to be able to quickly get the version and specify the config directory in case you are testing with different configurations and have multiple configs (this is likely moreso to be a useful features as more settings are added and switching between configs becomes more common)
I messed around with adding log level but I think it is confusing to users to have that be both a CLI arg and a setting in the config toml file so I kept the cli very simple for now. This should be easy to add to if more features are desired.
=> CLI Support

CONTRIBUTING.md, README.md
The previous readme did not specify that `cargo run`, `cargo fmt` and `cargo clippy` should be passing locally before committing. This may be obvious to those who are experienced in the Rust ecosystem, but for those who are not it is useful to specify and makes it easier for new contributors to quickly get up to speed. 
I moved the information regarding flame graph as well into the contributing file, since it is likely not relevant for most users unless they are contributing.  Finally, I chose to choose the name `CONTRIBUTING.md` instead of `HACKING.md` since `CONTRIBUTING.md` is more standardized, and has a specific special icon support in visual studio code among other support. (I also feel like long term, having a file called HACKING can be scary for non-technical users, even though …
=> update readme and add a contributing.md file

.github/workflows/ci.yml
this is pam-dbus-notify, to be more exact. Furthermore, I'm installing notify-send, to be able to test that sending notifications actually works as expected
=> preliminary try to add a notification daemon

README.md, cache/Cargo.toml, cache/benches/load_test.rs, cache/src/lib.rs, common/src/types.rs, input/src/lib.rs, odilia-notify/src/notification.rs, tts/src/lib.rs
fix build instructions in README
It is unnecessary to run `cargo build` before `cargo install`.
On my machine this causes Odilia` to be built twice, possibly because of different
build profiles.
Then the commit/push hooks prevented a push due to a number of compile and `Clippy` issues.
These are addressed in subsequent commits.
=> Fix build instructions

.github/workflows/ci.yml, Cargo.lock, odilia-notify/Cargo.toml, odilia-notify/src/action.rs, odilia-notify/src/lib.rs, odilia-notify/src/notification.rs, odilia-notify/src/urgency.rs
- Add `urgency` field to `Notification` struct
- Add `actions` field to `Notification` struct
- Use `itertools` for chunking vector items by pairs (chunks not available in `std::iter::Iterator` yet)
- Default: `Urgency::Normal`
- No custom `From<T>` for `Value` or `OwnedValue` (all done through `#[derive(...)]`)
=> Notification improvements

Cargo.lock, odilia/src/state.rs
Addresses https://github.com/odilia-app/odilia/issues/114 
According to Tait's message on Matrix:
> Yes. The issue is that the configuration file is required. In addition, it ignored /etc/odilia/, and only pays attention to $XDG_CONFIG_HOME/odilia/.
I want:
Odilia to detect configuration files both in /etc/odilia/, and $XDG_CONFIG_HOME/odilia.
Odilia should work without a configuration file, and it should apply the default config, if a known one is not used.
Obviously, prescience should be for command-line-flag (if given), followed by XDG_CONFIG_HOME, followed by /etc/odilia/ followed by "use the default, whatever that is".
This PR should support configuration in /etc/. It is cleaner than the old config code by using enums and matching. It prioritizes the order Tait gave. 
To be clear, if …
=> Allow etc system-wide config

Cargo.lock, Cargo.toml, input/Cargo.toml, input/src/lib.rs, odilia/Cargo.toml, odilia/src/events/mod.rs, odilia/src/main.rs, odilia/src/state.rs, tts/Cargo.toml, tts/src/lib.rs
this works as expected, minimising the use of channels, especially where they are not needed, when shutting down.
furthermore, based on my previous assessments, the tokens method of shutting down is more responsive, producing an imediate shutdown.
warning!
the last commit, which removed the last channel for shutdown purposes in use in the codebase that I could see, introduced the hanging bug again. I used gdb to trace it to somewhere around the `odilia::events::dispatch_wrapper` function, for no obvious reason.
Please don't merge this yet, more review is required. The previous commits except the last one are known to work perfectly, so the change seemns small, but apparently it has long ramifications I can't anticipate, and a cursory look at the affected code doesn't reveal anything of …
=> add cancellation tokens in stead of channels for shutting down

odilia/src/main.rs
We should not drop app names because some apps don't do it. Generally, it should work. Apps that do not comply with the standard would not have their name shown on notification daemons either, so we're still getting the same information.
=> Use app names in notiication speech

Cargo.lock, common/Cargo.toml, common/src/errors.rs, common/src/settings/log.rs, common/src/settings/mod.rs, common/src/settings/speech.rs, odilia/Cargo.toml, odilia/src/events/mod.rs, odilia/src/logging.rs, odilia/src/main.rs, odilia/src/state.rs
this makes the configuration system far more resiliant to problems, as well as introduces some composability to it. This is how configuration is sourced at the moment, feedback welcome:
* default: the configuration struct has a default value, which is computed with a specific implementation of the default trait
* env vars: environment variables for the options available in the configuration, prefixed with ODILIA_
* configuration file sent via a cli argument: if that argument is present, it will be converted to a path and then merged in with the rest
* XDG_CONFIG_HOME: the file at $XDG_CONFIG_HOME/odilia/config.toml will be used
* system wide: configuration from /etc/odilia/config.toml will be used
if any of those files don't exist, nothing will happen, because a good known default set is …
=> make configuration handling a lot better

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, cache/Cargo.toml, cache/benches/load_test.rs, cache/src/lib.rs, common/Cargo.toml, common/src/cache.rs, common/src/command.rs, common/src/errors.rs, common/src/lib.rs, odilia-notify/src/urgency.rs, odilia/Cargo.toml, odilia/src/events/cache.rs, odilia/src/events/object.rs, odilia/src/main.rs, odilia/src/state.rs, odilia/src/tower/cache_event.rs, odilia/src/tower/choice.rs, odilia/src/tower/from_state.rs, odilia/src/tower/handler.rs, odilia/src/tower/handlers.rs, odilia/src/tower/iter_svc.rs, odilia/src/tower/mod.rs, odilia/src/tower/service_ext.rs, odilia/src/tower/state_changed.rs, odilia/src/tower/unwrap_svc.rs, rust-toolchain.toml
First attempt at Axum-style state management. The final PR should have:
All should be able to implement some kind of state extraction, through types like the following:
Feel free to add additional items in the comments of this PR.
For right now, I've put together a basic `EventHandlers` type, that is able to connect up atspi events to various routers. At this time, I haven't seen how to add all the various parameters to a function yet, that's still to work on.
I'm hoping this makes for a more readable codebase. It sort of hides some of the complexity.
=> First attempt at basic axum-style state management

CONTRIBUTING.md
=> Add Feature Documentation
